# Generated by Django 4.1.5 on 2023-01-28 14:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogApp', '0003_alter_blogpost_job_offer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, default=None, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_content',
            field=models.TextField(default='..'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='job_offer_type',
            field=models.CharField(choices=[('Summer Internship', 'Summer Intership'), ('Winter Internship Only', 'Winter Intership Only'), ('Winter Internship & Job', 'Winter Internship & Job'), ('Job Only', 'Job Only')], default='Job Only', max_length=100),
        ),
    ]
