# Generated by Django 4.1.5 on 2023-01-29 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0006_remove_comment_post_comment_postcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='postcomments',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='postcomments', to='BlogApp.blogpost'),
        ),
    ]
