# Generated by Django 4.1.5 on 2023-01-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0008_blogpost_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='likecount',
            field=models.IntegerField(default=0),
        ),
    ]
