# Generated by Django 4.1.5 on 2023-01-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0009_blogpost_likecount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='likecount',
        ),
    ]
