# Generated by Django 4.1.5 on 2023-02-05 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0012_alter_account_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
