# Generated by Django 4.1.5 on 2023-02-06 09:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogApp', '0015_remove_comment_name_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.ManyToManyField(blank=True, default=None, related_name='name', to=settings.AUTH_USER_MODEL),
        ),
    ]
