# Generated by Django 4.1.5 on 2023-02-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0016_remove_comment_author_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
